/* soapClient.c
   Generated by gSOAP 2.8.3 from IPAWS.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.3 2011-10-13 00:40:18 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getRequest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__requestParameterList *ns1__getRequestTypeDef, struct ns3__responseParameterList *ns1__getResponseTypeDef)
{	struct __ns1__getRequest soap_tmp___ns1__getRequest;
	if (!soap_endpoint)
		soap_endpoint = "http://vvsoua7.fematdl.net:8210/IPAWS_CAPService/IPAWS";
	if (!soap_action)
		soap_action = "http://gov.fema.ipaws.services/IPAWS_CAPService/getRequest";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getRequest.ns1__getRequestTypeDef = ns1__getRequestTypeDef;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getRequest(soap, &soap_tmp___ns1__getRequest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getRequest(soap, &soap_tmp___ns1__getRequest, "-ns1:getRequest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getRequest(soap, &soap_tmp___ns1__getRequest, "-ns1:getRequest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getResponseTypeDef)
		return soap_closesock(soap);
	soap_default_ns3__responseParameterList(soap, ns1__getResponseTypeDef);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns3__responseParameterList(soap, ns1__getResponseTypeDef, "ns1:getResponseTypeDef", "ns3:responseParameterList");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__postCAP(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__postCAPRequestTypeDef *ns1__postCAPRequestTypeDef, struct _ns1__postCAPResponseTypeDef *ns1__postCAPResponseTypeDef)
{	struct __ns1__postCAP soap_tmp___ns1__postCAP;
	if (!soap_endpoint)
		soap_endpoint = "http://vvsoua7.fematdl.net:8210/IPAWS_CAPService/IPAWS";
	if (!soap_action)
		soap_action = "http://gov.fema.ipaws.services/IPAWS_CAPService/postCAP";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__postCAP.ns1__postCAPRequestTypeDef = ns1__postCAPRequestTypeDef;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__postCAP(soap, &soap_tmp___ns1__postCAP);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__postCAP(soap, &soap_tmp___ns1__postCAP, "-ns1:postCAP", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__postCAP(soap, &soap_tmp___ns1__postCAP, "-ns1:postCAP", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__postCAPResponseTypeDef)
		return soap_closesock(soap);
	soap_default__ns1__postCAPResponseTypeDef(soap, ns1__postCAPResponseTypeDef);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__postCAPResponseTypeDef(soap, ns1__postCAPResponseTypeDef, "ns1:postCAPResponseTypeDef", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getMessage(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__requestParameterList *ns1__getMessageTypeDef, struct _ns1__messageResponseTypeDef *ns1__messageResponseTypeDef)
{	struct __ns1__getMessage soap_tmp___ns1__getMessage;
	if (!soap_endpoint)
		soap_endpoint = "http://vvsoua7.fematdl.net:8210/IPAWS_CAPService/IPAWS";
	if (!soap_action)
		soap_action = "http://gov.fema.ipaws.services/IPAWS_CAPService/getMessage";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getMessage.ns1__getMessageTypeDef = ns1__getMessageTypeDef;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getMessage(soap, &soap_tmp___ns1__getMessage);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getMessage(soap, &soap_tmp___ns1__getMessage, "-ns1:getMessage", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getMessage(soap, &soap_tmp___ns1__getMessage, "-ns1:getMessage", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__messageResponseTypeDef)
		return soap_closesock(soap);
	soap_default__ns1__messageResponseTypeDef(soap, ns1__messageResponseTypeDef);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__messageResponseTypeDef(soap, ns1__messageResponseTypeDef, "ns1:messageResponseTypeDef", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
